In [ ]:
### importing required libraries
import pandas as pd

In [2]:
# function to read the parquet file

def read_parquet(location):
    df = pd.read_parquet(location)
    return df

In [3]:
df = read_parquet('output1.parquet')
df

,Date,Open,High,Low,Close,Adj Close,Volume,Symbol,Security Name
0,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A,"Agilent Technologies, Inc. Common Stock"
1,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A,"Agilent Technologies, Inc. Common Stock"
2,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A,"Agilent Technologies, Inc. Common Stock"
3,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A,"Agilent Technologies, Inc. Common Stock"
4,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A,"Agilent Technologies, Inc. Common Stock"
...,...,...,...,...,...,...,...,...,...
28126845,2020-03-26,10.230000,11.430000,10.230000,11.100000,11.100000,189500.0,ZYXI,"Zynex, Inc. - Common Stock"
28126846,2020-03-27,10.700000,10.980000,10.060000,10.300000,10.300000,145000.0,ZYXI,"Zynex, Inc. - Common Stock"
28126847,2020-03-30,10.160000,11.060000,10.160000,10.800000,10.800000,162300.0,ZYXI,"Zynex, Inc. - Common Stock"
28126848,2020-03-31,10.680000,11.140000,10.590000,11.070000,11.070000,280400.0,ZYXI,"Zynex, Inc. - Common Stock"
28126849,2020-04-01,11.160000,11.160000,10.510000,10.920000,10.920000,315900.0,ZYXI,"Zynex, Inc. - Common Stock"

In [4]:
# function for calculating rolling average and median

def apply_transformations(df):
    df['vol_moving_avg'] = df['Volume'].rolling(30).mean()
    df['adj_close_rolling_med'] = df['Volume'].rolling(30).median()
    return df

In [5]:
df = apply_transformations(df)
df

,Date,Open,High,Low,Close,Adj Close,Volume,Symbol,Security Name,vol_moving_avg,adj_close_rolling_med
0,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A,"Agilent Technologies, Inc. Common Stock",NaN,NaN
1,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A,"Agilent Technologies, Inc. Common Stock",NaN,NaN
2,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A,"Agilent Technologies, Inc. Common Stock",NaN,NaN
3,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A,"Agilent Technologies, Inc. Common Stock",NaN,NaN
4,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A,"Agilent Technologies, Inc. Common Stock",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
28126845,2020-03-26,10.230000,11.430000,10.230000,11.100000,11.100000,189500.0,ZYXI,"Zynex, Inc. - Common Stock",421296.666667,350400.0
28126846,2020-03-27,10.700000,10.980000,10.060000,10.300000,10.300000,145000.0,ZYXI,"Zynex, Inc. - Common Stock",422123.333333,350400.0
28126847,2020-03-30,10.160000,11.060000,10.160000,10.800000,10.800000,162300.0,ZYXI,"Zynex, Inc. - Common Stock",420873.333333,350400.0
28126848,2020-03-31,10.680000,11.140000,10.590000,11.070000,11.070000,280400.0,ZYXI,"Zynex, Inc. - Common Stock",420543.333333,350400.0
28126849,2020-04-01,11.160000,11.160000,10.510000,10.920000,10.920000,315900.0,ZYXI,"Zynex, Inc. - Common Stock",425813.333333,350400.0

In [6]:
# function to write the resulting dataset into parquet

def write_output_data(location, df):
    df.to_parquet(location)

In [7]:
if __name__ == '__main__':
    #location = "stage/outpu1.parquet"
    #out_loc = "stage/outpu2.parquet"
    location = input("Enter input file full location with the file name: ")
    out_loc = input("full location where you want to write the outfile file: ")
    df = read_parquet(location)
    df = apply_transformations(df)
    write_output_data(out_loc,df)

### Writing Unit Tests

In [8]:
# calculating rolling mean of the 30th row manually
s=0
for i in range(30):
    s = s + float(df['Volume'].iloc[i])    
s = s/30    

# calculating rolling mean of the 31st row manually
t=0
for i in range(1, 31):
    t = t + float(df['Volume'].iloc[i])    
t = t/30

In [9]:
import unittest

class Test(unittest.TestCase):

    def test_rolling_mean1(self):
        self.assertEqual(s, float(df['vol_moving_avg'].iloc[29]))
        
    def test_rolling_mean2(self):
        self.assertEqual(t, float(df['vol_moving_avg'].iloc[30]))

unittest.main(argv=[''], verbosity=2, exit=False)

test_rolling_mean1 (__main__.Test) ... ok
test_rolling_mean2 (__main__.Test) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK